Code review 2 😎
theAspiringDev1/MovieZone pull request #3
Opened 2020-08-30 10:03 UTC by theAspiringDev1

Sinubukan ko squash sa isang commit lahat para madali ata tingnan or mali po ba yun ?

2020-08-31 12:10 UTC, jorenrui requested changes
Regarding sa squash commit? I think di sya ok. Mas ok kung maraming multiple commits para anytime pwde ka mag reset or revert. Mas ok na mag merge and squash lang if mag memerge ka na ng PR. Kinda like

1. Have a master branch
2. Create a branch named feature-login-page
3. Code and create small and descriptive commits
4. After finishing and testing the code, create a PR entitled "Feature: Login Page" then add reviewers
5. Reviewers request changes
6. PR owner fix the requested changes
7. Reviewer approves the PR
8. PR gets "Squashed and Merged" - the commits gets "squashed" into one commit then get "merged" into master

Resulting Commit History for the master branch will become like this:

![image](https://user-images.githubusercontent.com/23741509/91717840-da7d8d00-ebc4-11ea-8b86-2c73ae440eb5.png)

As you can see, the PR's title is the commit message then the PR's description will become the commit's description. The PR number is also included for reference.


Also I think di nagana yung preview deploy?
https://movie-zone-git-code-review-2.theaspiringdev1.vercel.app

![image](https://user-images.githubusercontent.com/23741509/91717934-0bf65880-ebc5-11ea-8c33-02bd25d6bf7b.png)

I think di mo ata nalagyan ng Environment Variables yung preview deployment sa Vercel?

<img width="1077" alt="Screen Shot 2020-08-31 at 8 04 16 PM" src="https://user-images.githubusercontent.com/23741509/91718118-58da2f00-ebc5-11ea-8488-62fb7bf48c23.png">

Also tip, when writing commit messages. Check mo if bagay sya sa sentence na to:

This commit will ______

Ex. Add skeleton loader to movie list

Fit sya kasi:

This commit will add skeleton loader to movie list. 

Reference:
[How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/)

2020-08-31 12:10 UTC, jorenrui commented on src/hooks/usePersonDetails.js
> +                `https://api.themoviedb.org/3/person/${id}?api_key=${process.env.REACT_APP_KEY}&language=en-US`
How bout putting `https://api.themoviedb.org` into the `.env`? Kinda like:

```
API=https://api.themoviedb.org
```

Then for the Axios, you can create an instance like:
```javascript
const baseUrl = process.env.API;

export const instance = axios.create({
  baseURL,
});
```

Then in the fetcher you can do:
```javascript
import { instance } from './utils/axios';

const fetcher = ({ movieId }) => instance.get(`/movies/${movieId}`);
```

Since the axios instance has a base url, the resulting fetcher's URL would be:

```
https://api.themoviedb.org/movies/3
```

2020-08-31 12:10 UTC, jorenrui commented on src/components/pages/UpcomingMoviesPage.js
> +        history.push(`/error/${hasError}`);
I think this should be in a `useEffect`? Kinda like:
```javascript
useEffect(() => {
  if (hasError) {
    history.push(`/error${hasError}`);
  }
}, [hasError]);

if (!isLoading) {
  return <Collection />
}

return <PageSkeleton />
```

I'm just not sure of returning undefined here? I think it's more ok if you return a page skeleton rather than a blank page while the page is waiting for the redirect?

2020-08-31 12:10 UTC, jorenrui commented on src/components/pages/SearchResultsPage.js
> +        params: { query },
I think this is too much deconstructuring that it may affect readability?
Why not deconstruct the `match` variable then do it like this:

```javascript
export default function SearchPageResult({ match, history }) {
  const { query } = match.params;
```

2020-08-31 12:10 UTC, jorenrui commented on src/components/pages/SearchResultsPage.js
> +            pageLimit={pageLimit.total_pages}
Inconsitent style for `total_pages` or is this because this is the structure in the API you're using? I think it is standard in JavaScript to use `camelCase` for variables then `UPPERCASE` for constants. Then `kebab-case` for urls, then `snake_case` for database/backend?

2020-08-31 12:10 UTC, jorenrui commented on src/components/pages/GenrePage.js
> +        history.push(`/error/${hasError}`);
Question: why is the url can be like this:
```javascript
error/true
error/false
```

2020-08-31 12:10 UTC, jorenrui commented on src/components/pages/TVShowPage/Seasons/SeasonSkeleton/index.js
> +
Remove extra line?

2020-08-31 12:10 UTC, jorenrui commented on src/components/pages/Collection/index.js
> +                    {movies.length !== 0 ? (
How bout:
```javascript
{movies.length ? (
```

When length is 1 or more, it will be considered as `true`, then `false` when the length is 0.

2020-08-31 12:10 UTC, jorenrui commented on src/components/layout/Nav/index.js
> +            {<MobileNav isOpen={isOpen} setIsOpen={setIsOpen} />}
Remove unnecessary curly braces around the component?

2020-08-31 12:10 UTC, jorenrui commented on src/components/Slider/index.js
> +                        movies.map((movie) => (
How bout `movies?.map` rather than `movies && movies.map`?

2020-08-31 12:10 UTC, jorenrui commented on src/components/Search/index.js
> +    const location = useLocation();
How bout
```
const { pathname } = useLocation();

useEffect(() => {
  window.scrollTo(0,0,);
  setQuery("");
}, [pathname]);
```

or is this not possible?

2020-08-31 12:10 UTC, jorenrui commented on src/components/Reviews/index.js
> +                {data.results.length !== 0 ? (
`data.results.length !== 0 ? (` > `data.results.length ? (`?

2020-08-31 22:55 UTC, theAspiringDev1 commented on src/components/pages/UpcomingMoviesPage.js
> +        history.push(`/error/${hasError}`);
Oo nga noh \(@^0^@)/

2020-08-31 23:11 UTC, theAspiringDev1 commented on src/components/pages/SearchResultsPage.js
> +            pageLimit={pageLimit.total_pages}
ganun po ung keys ng results from the api

2020-08-31 23:11 UTC, theAspiringDev1 commented on src/components/pages/Collection/index.js
> +                    {movies.length !== 0 ? (
Salamat ulit dito ate \(￣︶￣*\))

2020-09-01 06:27 UTC, jorenrui commented on src/components/pages/SearchResultsPage.js
> +            pageLimit={pageLimit.total_pages}
Okiee~

2020-09-10 00:12 UTC, closed without merging